print_info() {
    info title
    info underline

    info "OS" distrotmp
    info "Kernel" kernel
    info "Uptime" uptime
    info "Pkgs" packages
    info "Shell" shell
    info "WM" wm
    info "RAM" memory
    info "Disk" disk
    info "Battery" battery

    info cols
}

color_blocks="off" # Keeps output clean like fastfetch
separator=" ➜ "

ascii_distro="artix_small"
gap=1
